devices([
	"iPhone 7 Plus",
	"iPhone 7"
])

languages([
	"en-US",
])

scheme "Depoza"

output_directory "./screenshots"

clear_previous_screenshots true

workspace "./Depoza.xcworkspace"

number_of_retries 0

stop_after_first_error true